//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_users
    {
        public int id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public int role { get; set; }
    
        public virtual t_usersType t_usersType { get; set; }
    }
}
